# Generated by Django 5.2.17 on 2026-08-30 06:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkaccount',
            name='avatar',
            field=models.ImageField(choices=[('classic', 'defaults/default_user_photo_1.png'), ('violet', 'defaults/default_user_photo_2.png'), ('space', 'defaults/default_user_photo_3.png')], default=account.models.random_default_avatar, upload_to=account.models.avatar_path, verbose_name='Аватар'),
        ),
    ]
