# Generated by Django 5.2.17 on 2026-08-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_darkaccount_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkaccount',
            name='avatar_access',
            field=models.CharField(choices=[('all', 'Все'), ('authenticated', 'Аутентифицированные'), ('nobody', 'Никто')], default='all', verbose_name='Доступ к аватару'),
        ),
    ]
