# Generated by Django 5.2.17 on 2026-08-30 06:54

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_darkaccount_avatar_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkaccount',
            name='avatar',
            field=models.ImageField(default=account.models.random_default_avatar, upload_to=account.models.avatar_path, verbose_name='Аватар'),
        ),
    ]
