# Generated by Django 5.2.17 on 2026-09-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stlm/concerts/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('past', 'Прошедший'), ('cancelled', 'Отменённый')], default='upcoming', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stlm/merch/')),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('tshirt', 'Одежда'), ('poster', 'Плакат'), ('sticker', 'Стикер'), ('other', 'Другое')], default='other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='stlm/music/')),
                ('file', models.FileField(blank=True, null=True, upload_to='stlm/music_files/')),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='stlm/avatars/')),
                ('role', models.CharField(choices=[('vocalist', 'Вокал'), ('guitarist', 'Гитара'), ('drummer', 'Барабаны'), ('lyricist', 'Тексты'), ('programmer', 'Кодер'), ('other', 'Другое')], default='other', max_length=50)),
                ('member_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='stlm/albums/')),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('album', 'Альбом'), ('single', 'Сингл'), ('debut', 'дебют')], default='album', max_length=50)),
                ('music', models.ManyToManyField(blank=True, to='stlm.music')),
            ],
        ),
    ]
