# Generated by Django 5.2.17 on 2026-09-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_date', 'title'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.AlterModelOptions(
            name='merch',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-release_date', 'title'], 'verbose_name': 'Музыку', 'verbose_name_plural': 'Музыка'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['name'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stlm/albums/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='album',
            name='music',
            field=models.ManyToManyField(blank=True, to='stlm.music', verbose_name='Музыка'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('album', 'Альбом'), ('single', 'Сингл'), ('debut', 'дебют')], default='album', max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stlm/concerts/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Предстоящий'), ('past', 'Прошедший'), ('cancelled', 'Отменённый')], default='upcoming', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stlm/merch/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='type',
            field=models.CharField(choices=[('tshirt', 'Одежда'), ('poster', 'Плакат'), ('sticker', 'Стикер'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='stlm/music_files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stlm/music/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateField(verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='stlm/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='member_photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото участника'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('vocalist', 'Вокал'), ('guitarist', 'Гитара'), ('drummer', 'Барабаны'), ('lyricist', 'Тексты'), ('programmer', 'Кодер'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Роль'),
        ),
    ]
