# Generated by Django 5.2.17 on 2026-09-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stlm', '0002_alter_album_options_alter_concert_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='stock_quantity',
        ),
    ]
