# Generated by Django 5.2.17 on 2026-08-27 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prefix', models.CharField(default='DZ', max_length=50, verbose_name='Префикс(например `DZ`)')),
                ('id_number', models.PositiveIntegerField(verbose_name='Номер(например `1`)')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('threat_class', models.CharField(choices=[('ATHENA', 'Афина'), ('HERMES', 'Гермес'), ('HEPHAESTUS', 'Гефест'), ('PROMETHEUS', 'Прометей'), ('HADES', 'Аид')], default='ATHENA', max_length=50, verbose_name='Класс угрозы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание(html)')),
                ('anomalous_properties', models.TextField(blank=True, null=True, verbose_name='Аномальные свойства(html)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='anomalies/', verbose_name='Изображение')),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись к изображению')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Аномалия',
                'verbose_name_plural': 'Аномалии',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('callsign', models.CharField(blank=True, max_length=100, null=True, verbose_name='Позывной')),
                ('personnel_class', models.CharField(choices=[('A', 'Класс A'), ('B', 'Класс B'), ('C', 'Класс C'), ('D', 'Класс D'), ('E', 'Класс E'), ('F', 'Класс F'), ('G', 'Класс G'), ('H', 'Класс H'), ('I', 'Класс I'), ('J', 'Класс J'), ('K', 'Класс K'), ('L', 'Класс L'), ('M', 'Класс M'), ('N', 'Класс N'), ('O', 'Класс O'), ('P', 'Класс P'), ('Q', 'Класс Q'), ('R', 'Класс R'), ('S', 'Класс S'), ('T', 'Класс T'), ('U', 'Класс U'), ('V', 'Класс V'), ('W', 'Класс W'), ('X', 'Класс X'), ('Y', 'Класс Y'), ('Z1', 'Класс Z-1'), ('Z2', 'Класс Z-2')], max_length=50, verbose_name='Класс персонала')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('DECEASED', 'Погиб'), ('RETIRED', 'В отставке'), ('MIA', 'Пропал без вести')], default='ACTIVE', max_length=50, verbose_name='Статус')),
                ('biography', models.TextField(verbose_name='Биографическая справка(html)')),
                ('psych_profile', models.TextField(verbose_name='Психологический портрет(html)')),
                ('quote', models.TextField(blank=True, null=True, verbose_name='Известная цитата')),
                ('service_marks', models.JSONField(blank=True, default=list, verbose_name='Служебные отметки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='personnel/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название инцидента')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата инцидента')),
                ('description', models.TextField(verbose_name='Описание инцидента(html)')),
                ('course_of_events', models.JSONField(default=list, verbose_name='Ход событий[список событий]')),
                ('consequences', models.TextField(verbose_name='Последствия(html)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='DZ.anomaly', verbose_name='Аномалия')),
            ],
        ),
        migrations.CreateModel(
            name='InterrogationProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название протокола')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата составления')),
                ('interrogator', models.CharField(max_length=255, verbose_name='Допрашивающий')),
                ('interrogated_person', models.CharField(max_length=255, verbose_name='Допрашиваемый')),
                ('dialogue', models.TextField(verbose_name='Диалог')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogation_protocols', to='DZ.anomaly', verbose_name='Связанный объект')),
            ],
        ),
        migrations.CreateModel(
            name='NotClassifiedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата составления')),
                ('data', models.TextField(verbose_name='Данные')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_classified_materials', to='DZ.anomaly', verbose_name='Связанный объект')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название зоны')),
                ('location', models.CharField(max_length=255, verbose_name='Расположение')),
                ('status', models.CharField(choices=[('ACTIVE', 'Функционирует'), ('DECOMMISSIONED', 'Заброшена'), ('DESTROYED', 'Уничтожена')], default='ACTIVE', max_length=50, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Общая информация')),
                ('specialization', models.TextField(verbose_name='Специализация')),
                ('command_staff', models.IntegerField(blank=True, null=True, verbose_name='Командный состав')),
                ('scientific_staff', models.IntegerField(blank=True, null=True, verbose_name='Научный персонал (F, G, H)')),
                ('security_personnel', models.IntegerField(blank=True, null=True, verbose_name='Персонал безопасности (I, J, K)')),
                ('administrative_technical_staff', models.IntegerField(blank=True, null=True, verbose_name='Административный и технический персонал')),
                ('class_a_personnel', models.IntegerField(blank=True, null=True, verbose_name='Персонал класса А')),
                ('x', models.FloatField(verbose_name='Координата X')),
                ('y', models.FloatField(verbose_name='Координата Y')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_zones', to='DZ.personnel', verbose_name='Командир Зоны')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.AddField(
            model_name='anomaly',
            name='containment_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DZ.zone', verbose_name='Зона содержания'),
        ),
        migrations.AlterUniqueTogether(
            name='anomaly',
            unique_together={('id_prefix', 'id_number')},
        ),
    ]
