# Generated by Django 5.2.17 on 2026-08-27 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_type', models.CharField(choices=[('direct', 'Личный чат'), ('group', 'Групповой чат')], db_index=True, default='direct', max_length=10, verbose_name='Тип чата')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_avatars/', verbose_name='Аватар чата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('file', 'Файл'), ('system', 'Системное')], default='text', max_length=10, verbose_name='Тип сообщения')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/', verbose_name='Вложение')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Название вложения')),
                ('attachment_size', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер вложения')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='Чат')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='Ответ на сообщение')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Участник'), ('admin', 'Администратор'), ('owner', 'Владелец')], default='member', max_length=10, verbose_name='Роль')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Без уведомлений')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='chat.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message', verbose_name='Последнее прочитанное сообщение')),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чатов',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=32, verbose_name='Эмодзи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на сообщение',
                'verbose_name_plural': 'Реакции на сообщения',
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прочтения')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='chat.message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прочтение сообщения',
                'verbose_name_plural': 'Прочтения сообщений',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created_at'], name='chat_messag_chat_id_013eed_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='chat_messag_sender__62c9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'chat'], name='chat_chatpa_user_id_c46732_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('chat', 'user'), name='unique_chat_participant'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='unique_message_reaction'),
        ),
        migrations.AddIndex(
            model_name='messageread',
            index=models.Index(fields=['user', '-read_at'], name='chat_messag_user_id_b47113_idx'),
        ),
        migrations.AddConstraint(
            model_name='messageread',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_read'),
        ),
    ]
