# Generated by Django 5.2.17 on 2026-09-08 16:37

import django.db.models.deletion
import mail.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryemail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailbox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporaryemail',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=mail.models.default_expires_at, null=True),
        ),
    ]
